//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClientCallBack.WCFServiceCallback {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceCallback.IService", CallbackContract=typeof(TestClientCallBack.WCFServiceCallback.IServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GetData")]
        void GetData();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IService/GetData")]
        System.Threading.Tasks.Task GetDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTest", ReplyAction="http://tempuri.org/IService/GetTestResponse")]
        bool GetTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetTest", ReplyAction="http://tempuri.org/IService/GetTestResponse")]
        System.Threading.Tasks.Task<bool> GetTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Subscribe", ReplyAction="http://tempuri.org/IService/SubscribeResponse")]
        int Subscribe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Subscribe", ReplyAction="http://tempuri.org/IService/SubscribeResponse")]
        System.Threading.Tasks.Task<int> SubscribeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Unsubscribe", ReplyAction="http://tempuri.org/IService/UnsubscribeResponse")]
        bool Unsubscribe(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Unsubscribe", ReplyAction="http://tempuri.org/IService/UnsubscribeResponse")]
        System.Threading.Tasks.Task<bool> UnsubscribeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendResultBroadcast", ReplyAction="http://tempuri.org/IService/SendResultBroadcastResponse")]
        void SendResultBroadcast(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendResult", ReplyAction="http://tempuri.org/IService/SendResultResponse")]
        void SendResult(int id, string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : TestClientCallBack.WCFServiceCallback.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.DuplexClientBase<TestClientCallBack.WCFServiceCallback.IService>, TestClientCallBack.WCFServiceCallback.IService {
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void GetData() {
            base.Channel.GetData();
        }
        
        public System.Threading.Tasks.Task GetDataAsync() {
            return base.Channel.GetDataAsync();
        }
        
        public bool GetTest() {
            return base.Channel.GetTest();
        }
        
        public System.Threading.Tasks.Task<bool> GetTestAsync() {
            return base.Channel.GetTestAsync();
        }
        
        public int Subscribe() {
            return base.Channel.Subscribe();
        }
        
        public System.Threading.Tasks.Task<int> SubscribeAsync() {
            return base.Channel.SubscribeAsync();
        }
        
        public bool Unsubscribe(int id) {
            return base.Channel.Unsubscribe(id);
        }
        
        public System.Threading.Tasks.Task<bool> UnsubscribeAsync(int id) {
            return base.Channel.UnsubscribeAsync(id);
        }
    }
}
